name: Build Plugin
on:
  push:
    tags:
      - '*'
  workflow_dispatch:
    inputs: {}

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ghidra: ["9.1", "9.1.1", "9.1.2", "9.2", "9.2.1", "9.2.2", "9.2.3", "9.2.4", "10.0", "10.0.1", "DEV"]
        include:
          - ghidra: 9.1
            gradle: 6.9
          - ghidra: 9.1.1
            gradle: 6.9
          - ghidra: 9.1.2
            gradle: 6.9
          - ghidra: 9.2
            gradle: 6.9
          - ghidra: 9.2.1
            gradle: 6.9
          - ghidra: 9.2.2
            gradle: 6.9
          - ghidra: 9.2.3
            gradle: 6.9
          - ghidra: 9.2.4
            gradle: 6.9
          - ghidra: 10.0
            gradle: 7.1.1
          - ghidra: 10.0.1
            gradle: 7.1.1
          - ghidra: 10.0.2
            gradle: 7.1.1
          - ghidra: 10.0.3
            gradle: 7.1.1
          - ghidra: 10.0.4
            gradle: 7.1.1
          - ghidra: 10.1
            gradle: 7.1.1
          - ghidra: 10.1.1
            gradle: 7.1.1
          - ghidra: 10.1.2
            gradle: 7.1.1
          - ghidra: DEV
            gradle: current
    continue-on-error: ${{ matrix.ghidra == 'DEV' }}
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: "11"
          java-package: jdk
          architecture: x64
      - name: "Install official ghidra release"
        uses: er28-0652/setup-ghidra@master
        if: ${{ matrix.ghidra != 'DEV' }}
        with:
          version: ${{ matrix.ghidra }}
      - name: "Install an in-dev ghidra release (step 1)"
        if: ${{ matrix.ghidra == 'DEV' }}
        uses: robinraju/release-downloader@v1
        with:
          repository: "roblabla/ghidra-ci"
          latest: true
          fileName: "release.zip"
      - name: "Install an in-dev ghidra release (step 2)"
        uses: ihiroky/extract-action@v1
        if: ${{ matrix.ghidra == 'DEV' }}
        with:
          file_path: release.zip
          extract_dir: "/tmp/ghidra-dev"
      - name: "Install an in-dev ghidra release (step 3)"
        if: ${{ matrix.ghidra == 'DEV' }}
        run: |
          GHIDRA_INSTALL_DIR=$(echo /tmp/ghidra-dev/*)
          echo "Setting GHIDRA_INSTALL_DIR to $GHIDRA_INSTALL_DIR"
          echo "GHIDRA_INSTALL_DIR=$GHIDRA_INSTALL_DIR" >> $GITHUB_ENV
      - uses: eskatos/gradle-command-action@v1
        with:
          gradle-version: ${{ matrix.gradle }}
          arguments: -PGHIDRA_INSTALL_DIR=${{ env.GHIDRA_INSTALL_DIR }} addShadowJar
      - name: Find dist file
        id: find-dist
        run: echo ::set-output name=dist::$(ls dist/*-SHADOW.zip)
      - uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ steps.find-dist.outputs.dist }}
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true
